# Generated by Django 3.1.7 on 2021-09-15 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=5)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LithiumBattery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=20, null=True)),
                ('battery_voltage', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('battery_current', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('battery_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('rated_input_voltage', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('rated_input_current', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('charger_voltage', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('charger_current', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('purchase_period', models.DateField(auto_now_add=True)),
                ('charging_start_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('loss', models.DecimalField(decimal_places=2, default=1.2, max_digits=20)),
                ('min_voltage', models.DecimalField(decimal_places=2, default=3.7, max_digits=20)),
                ('max_voltage', models.DecimalField(decimal_places=2, default=4.2, max_digits=20)),
                ('start_battery', models.DecimalField(decimal_places=3, default=30, max_digits=20)),
                ('want_battery', models.DecimalField(decimal_places=3, default=30, max_digits=20)),
                ('time_prediction', models.DecimalField(decimal_places=3, default=30, max_digits=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.member')),
            ],
        ),
    ]
